### ISSUE TITLE
Didn't understand how to use the UI.

### ISSUE THREAD

**Issue by ghpkishore** [AI4Bharat/IndianNLP-Transliteration#3]
Might seem stupid. But does it translate stuff written in english to Indian languages or is it that you write a word in say Hindi in English font and it provides you the Indian option of it. Please do help me out. TIA!

**Comment by GokulNC** [comment]
No, this is not a translator.

If you type "samosa" in English, it will give you "समोसा" in Hindi.
This is called transliteration. (Do not confuse with translation)
