### ISSUE TITLE
Support transliteration for Odia language

### ISSUE THREAD

**Issue by soumendrak** [AI4Bharat/IndianNLP-Transliteration#7]
Support transliteration for Odia language. I am interested if anybody guides me on how to implement it.

**Comment by JosephGeoBenjamin** [comment]
@soumendrak Thanks for Your interest.  It all starts with Good quality data, for Odia we could not find a good source of transliteration datasets covering common words (not just nouns as in named entity corpus). If there are any such sources with a non-restrictive license that you might be aware of, feel free to let us know.

If there is some source of such data, then training the RNN models is straight forward using the scripts from this repo. which you can add support and give us a pull request and link to model checkpoints to be added to release.

**Comment by soumendrak** [comment]
Thanks for replying @JosephGeoBenjamin 

- Can you please describe in detail what kind of data with schema is needed?
- If it is not there, we will create it for the Odia language.

Thank you. 🙏🏼

**Comment by GokulNC** [comment]
Please check one of these datasets for sample format:
https://transliteration.ai4bharat.org/#/resources

**Comment by soumendrak** [comment]
I will get back on this. Thank you for the support. 🙏🏼
